### ISSUE TITLE
Forget after backup - stalls

### ISSUE THREAD

**Issue by psyciknz** [djmaze/resticker#168]
```restic-backup           | Files:       37132 new, 27702 changed, 1147947 unmodified
restic-backup            | Dirs:         5485 new,   415 changed, 193964 unmodified
restic-backup            | Data Blobs:   2789 new
restic-backup            | Tree Blobs:   5585 new
restic-backup            | Added to the repository: 1.215 GiB (1.215 GiB stored)
restic-backup            |
restic-backup            | processed 1212781 files, 270.371 GiB in 29:20
restic-backup            | snapshot d278d44c saved
restic-backup            | Backup successful
restic-backup            | Forget about old snapshots based on RESTIC_FORGET_ARGS = --keep-last 10 --keep-daily 2 --keep-weekly 1 --keep-monthly 1 --tag Drogo
restic-backup            | Fatal: unable to create lock in backend: repository is already locked by PID 129 on raspups by root (UID 0, GID 0)
restic-backup            | lock was created at 2023-06-20 13:15:14 (4m35.219845879s ago)
restic-backup            | storage ID a07f901e`
```

Trying to resolve this situation, this is a forget running after a backup.  So it doesn't tend to execute the post_command in this situation.  When this scenario occurs, does it attempt to retry, or will complete at some point?

**Comment by thierrybla** [comment]
I also run into this issue.

**Comment by mentos1386** [comment]
I have the same issue. My container is constantly restarting due to this.

**Comment by thierrybla** [comment]
I fixed it by doing a manual unlock, now the forget / prune works as expected.

**Comment by psyciknz** [comment]
Yeah that's the only way I fix it as well.  Ideally a retry or something would be handy.

**Comment by djmaze** [comment]
Not sure if a retry is always the right thing to do here. I have situations where a long running prune is still ongoing or even crashed. That's when waiting does not solve the problem, but you need to manually unlock.

I think the forget is not that important. If it fails, the container should just go back to its schedule and wait for the next backup cron trigger. IMO.

**Comment by thierrybla** [comment]
Would it be possible to add an unlock on a schedule?

**Comment by thierrybla** [comment]
> I think the forget is not that important. If it fails, the container should just go back to its schedule and wait for the next backup cron trigger. IMO.

Yes it will, but even the next or any forget after the first failed one does not work. You really should manually unlock before the next forget will work once or twice and it goes back to staying locked.

Is it not possible to throw a unlock before the forget command comes through?

**Comment by djmaze** [comment]
I think I don't really understand. @thierrybla If your repository stays lock every few runs, something is broken in your setup. Maybe you have prunes running in parallel?

**Comment by duncan4000** [comment]
kind of late to the party but related, 

i find this happens and is repeatable for me if i have the --prune listed in the restic_forget_args. 
will continue to lock even if i remove locks manually. remove the --prune command and everything runs with no errors. n

what cleared the issue was running a separate docker container for just prune just once. 

this seems to have cleared the issue in the restic repo now and --prune argument no longer locks up and throws the already locked error. 

would be keen for a fix for this however as this triggered a lot of repeat backups to B2 and blew up my transactions. lesson learnt on that, Run on startup is now set to false.

**Comment by djmaze** [comment]
I guess this might be because prune takes a long time, maybe even until the next backup run is supposed to occur?

I really recommend running a separate prune container, on a separate schedule, which does not conflict with the backups, in order to prevents problems like this.

**Comment by duncan4000** [comment]
Nope unfortunately not the issue here. 

Ive Tested this on very small backups with 24hr schedules. The prune was easily completing in the timeframe. But the error was still occuring.

**Comment by djmaze** [comment]
Right, I think I see now why an error during `forget` ends the script / stops the container. Will fix that.

Still not sure why a lock might remain if the previous prune was successfully finished long before. @duncan4000 Which backend are you using?

**Comment by duncan4000** [comment]
Using docker on windows. Ubuntu via WSL. Which I admit was creating tons of issues not just with this. 

Ive since moved over to just straight Linux. But have not reconfigured this to confirm if the error still exists

**Comment by djmaze** [comment]
The just released v1.8.0 should fix the restarting of the container.
